dependencies:
- name: elasticsearch
  repository: http://helm.elastic.co 
  version: 7.3.0
  condition: "elasticsearch.enabled"
- name: kibana
  repository: http://helm.elastic.co 
  version: 7.3.0
  condition: "kibana.enabled"
  
