# Default values for zeebe-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elasticsearch:
  enabled: true
  imageTag: 6.8.1
  replicas: 3
  # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"
  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"
  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 100M
  extraInitContainers: | 
    - name: create
      image: busybox:1.28
      command: ['mkdir', '/usr/share/elasticsearch/data/nodes/']  
      volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: elasticsearch-master
    - name: file-permissions
      image: busybox:1.28
      command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
      volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: elasticsearch-master    
kibana:
  enabled: false
  imageTag: 6.8.1

replicaCount: 3
JavaOpts: |
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap
  -Xms1024m
  -Xmx1024m
image:
  repository: camunda/zeebe
  tag: 0.20.0
  pullPolicy: IfNotPresent
labels:
  app: zeebe  
service:
  type: ClusterIP
  http:
    port: 9600
  gateway:
    port: 26500
  command:
    port: 26501  
  internal:
    port: 26502
resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
global: 
  zeebe:
    elasticsearch:
      url: "http://elasticsearch-master:9200" 
