apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-gateway" (tpl .Values.global.zeebe .) | quote }}
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ tpl .Values.global.zeebe . }}-gateway
  annotations:
{{- toYaml  .Values.annotations | nindent 4 }}   
spec:
  selector:
    app: {{ tpl .Values.global.zeebe . }}-gateway 
  ports:
    - port: {{ .Values.service.http.port }}
      protocol: TCP
      name: {{ .Values.service.http.name | default "http" }}
    - port: {{ .Values.service.gateway.port }}
      protocol: TCP
      name: {{ .Values.service.gateway.name | default "gateway" }}