apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-gateway" (tpl .Values.global.zeebe .) | quote }}
  labels:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ tpl .Values.global.zeebe . | quote }}
  annotations:
{{- toYaml  .Values.annotations | nindent 4 }}   
spec:
  selector:
    app.kubernetes.io/name: {{ include "zeebe-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
    app: {{ tpl .Values.global.zeebe . | quote }}
  ports:
    - port: {{ .Values.serviceHttpPort }}
      protocol: TCP
      name: {{ default "http" .Values.serviceHttpName  }}
    - port: {{ .Values.serviceGatewayPort }}
      protocol: TCP
      name: {{ default "gateway" .Values.serviceGatewayName }}